#!/bin/sh
# remove prvious sockpaths
rm /tmp/sockpath
gcc -c utils.c -o utils.o
gcc utils.o server.c -o server -lpthread
gcc utils.o backup.c -o backup -lpthread
gcc utils.o client.c -o client
rm utils.o
echo 'compiled'
