/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct bufsize *bufptr;

struct bufsize {
	char buffer[1024];
	u_int size;
};
typedef struct bufsize bufsize;

struct file_args_r {
	char filename[128];
	u_int offset;
	u_int size;
};
typedef struct file_args_r file_args_r;

struct file_args_w {
	char filename[128];
	u_int offset;
	char buffer[1024];
	u_int size;
};
typedef struct file_args_w file_args_w;

#define nfs_arya 0x2fffffff
#define nfs 1

#if defined(__STDC__) || defined(__cplusplus)
#define nfs_ls 1
extern  bufsize * nfs_ls_1(file_args_r *, CLIENT *);
extern  bufsize * nfs_ls_1_svc(file_args_r *, struct svc_req *);
#define nfs_write 2
extern  int * nfs_write_1(file_args_w *, CLIENT *);
extern  int * nfs_write_1_svc(file_args_w *, struct svc_req *);
#define nfs_read 3
extern  bufsize * nfs_read_1(file_args_r *, CLIENT *);
extern  bufsize * nfs_read_1_svc(file_args_r *, struct svc_req *);
#define nfs_cd 4
extern  int * nfs_cd_1(file_args_r *, CLIENT *);
extern  int * nfs_cd_1_svc(file_args_r *, struct svc_req *);
extern int nfs_arya_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nfs_ls 1
extern  bufsize * nfs_ls_1();
extern  bufsize * nfs_ls_1_svc();
#define nfs_write 2
extern  int * nfs_write_1();
extern  int * nfs_write_1_svc();
#define nfs_read 3
extern  bufsize * nfs_read_1();
extern  bufsize * nfs_read_1_svc();
#define nfs_cd 4
extern  int * nfs_cd_1();
extern  int * nfs_cd_1_svc();
extern int nfs_arya_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bufptr (XDR *, bufptr*);
extern  bool_t xdr_bufsize (XDR *, bufsize*);
extern  bool_t xdr_file_args_r (XDR *, file_args_r*);
extern  bool_t xdr_file_args_w (XDR *, file_args_w*);

#else /* K&R C */
extern bool_t xdr_bufptr ();
extern bool_t xdr_bufsize ();
extern bool_t xdr_file_args_r ();
extern bool_t xdr_file_args_w ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
