/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "nfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

bufsize *
nfs_ls_1(file_args_r *argp, CLIENT *clnt)
{
	static bufsize clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, nfs_ls,
		(xdrproc_t) xdr_file_args_r, (caddr_t) argp,
		(xdrproc_t) xdr_bufsize, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
nfs_write_1(file_args_w *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, nfs_write,
		(xdrproc_t) xdr_file_args_w, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bufsize *
nfs_read_1(file_args_r *argp, CLIENT *clnt)
{
	static bufsize clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, nfs_read,
		(xdrproc_t) xdr_file_args_r, (caddr_t) argp,
		(xdrproc_t) xdr_bufsize, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
