/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
nfs_arya_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		bufnode nfs_ls_1_arg;
		file_args_w nfs_write_1_arg;
		file_args_r nfs_read_1_arg;
		bufnode nfs_cd_1_arg;
		bufnode getattr_1_arg;
		bufnode setattr_1_arg;
		bufnode nfs_remove_1_arg;
		bufnode nfs_mkdir_1_arg;
		bufnode nfs_touch_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case nfs_ls:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_bufnode;
		local = (char *(*)(char *, struct svc_req *)) nfs_ls_1_svc;
		break;

	case nfs_write:
		_xdr_argument = (xdrproc_t) xdr_file_args_w;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nfs_write_1_svc;
		break;

	case nfs_read:
		_xdr_argument = (xdrproc_t) xdr_file_args_r;
		_xdr_result = (xdrproc_t) xdr_bufnode;
		local = (char *(*)(char *, struct svc_req *)) nfs_read_1_svc;
		break;

	case nfs_cd:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nfs_cd_1_svc;
		break;

	case getattr:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_bufnode;
		local = (char *(*)(char *, struct svc_req *)) getattr_1_svc;
		break;

	case setattr:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) setattr_1_svc;
		break;

	case nfs_remove:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nfs_remove_1_svc;
		break;

	case nfs_mkdir:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nfs_mkdir_1_svc;
		break;

	case nfs_touch:
		_xdr_argument = (xdrproc_t) xdr_bufnode;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nfs_touch_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (nfs_arya, nfs);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, nfs_arya, nfs, nfs_arya_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (nfs_arya, nfs, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, nfs_arya, nfs, nfs_arya_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (nfs_arya, nfs, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
