/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"

#include <string.h>
#include <stdlib.h>
#include <unistd.h>

int getCommandType(char * str) {
	if(strcmp("ls", str) == 0) {
		return 1; // ls -> 1
	} else if(strcmp("read", str) == 0) {
		return 2; // read -> 2
	} else if(strcmp("write", str) == 0) {
		return 3; // write -> 3
	} else if(strcmp("exit", str) == 0) {
		return 0; // exit -> 0
	} else if(strcmp("cd", str) == 0) {
		return 4;  // cd -> 4
	} else if(strcmp("getattr", str) == 0) {
		return 5; // getattr -> 5
	} else if(strcmp("setattr", str) == 0) {
		return 6; // setattr -> 6
	} else if(strcmp("remove", str) == 0) {
		return 7; // remove -> 7
	} else if(strcmp("mkdir", str) == 0) {
		return 8; // mkdir -> 8
	} else if(strcmp("touch", str) == 0) {
		return 9; // touch -> 9
	}
	return -1;
}

int perm_bit (char * args) {
	int i, coff=1, perm=0;
    for(i=strlen(args)-1; i>=0; i--) {
        perm += (args[i]-'0')*coff;
        coff *= 8;
    }
	return perm;
}

void
nfs_arya_1(char *host)
{
	CLIENT *clnt;
	bufnode  *result_1;
	bufnode  nfs_ls_1_arg;
	int  *result_2;
	file_args_w  nfs_write_1_arg;
	bufnode  *result_3;
	file_args_r  nfs_read_1_arg;
	int  *result_4;
	bufnode  nfs_cd_1_arg;
	bufnode  *result_5;
	bufnode  getattr_1_arg;
	int  *result_6;
	bufnode  setattr_1_arg;
	int  *result_7;
	bufnode  nfs_remove_1_arg;
	int  *result_8;
	bufnode  nfs_mkdir_1_arg;
	int  *result_9;
	bufnode  nfs_touch_1_arg;
	char * args[4]; char buffer[1024], * tok; int i;
#ifndef	DEBUG
	clnt = clnt_create (host, nfs_arya, nfs, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	while(1) {
		printf("arya@nfs~$ ");
		fgets(buffer, 1024, stdin);
		tok = strtok(buffer, " \n");
		char * savecmd = tok;
		for (i = 0; i < 4; ++i){
			tok = strtok(NULL, " ");
			if(tok == NULL)	break;
			args[i] = tok;
		}
		switch(getCommandType(savecmd)) {
			case 0: // exit
				printf("Byee !\n");
				exit(1);
				break;
			case 1: // listing files
				if(i!=1){
					printf("usage: ls <dir_name>\n");
					break;
				}
				nfs_ls_1_arg.size = 0;
				strtok(args[0], "\n");
				strcpy(nfs_ls_1_arg.buffer, args[0]);

				result_1 = nfs_ls_1(&nfs_ls_1_arg, clnt);
				if (result_1 == (bufnode *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("Read %d files and dirs\n", result_1->size);
					printf("%s\n", result_1->buffer);
				}
				break;
			case 2: // reading files
				if(i!=3) {
					printf("usage: read <filename> <offset> <size>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(nfs_read_1_arg.filename, args[0]);
				nfs_read_1_arg.offset = atoi(args[1]);
				nfs_read_1_arg.size = atoi(args[2]);
				// printf("%s %d %d\n", nfs_read_1_arg.filename, nfs_read_1_arg.offset, nfs_read_1_arg.size);
				result_3 = nfs_read_1(&nfs_read_1_arg, clnt);
				if (result_3 == (bufnode *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(result_3->size < 0) {
						printf("File Reading error Occured !\n");
					} else {
						printf("Read %d bytes\n", result_3->size);
						printf("%s\n", result_3->buffer);
					}
				}
				break;
			case 3: // writing files
				if(i!=4){
					printf("usage: write <filename> <msg_without_blanks> <offset> <size>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(nfs_write_1_arg.filename, args[0]);
				strtok(args[1], "\n");
				strcpy(nfs_write_1_arg.buffer, args[1]);
				nfs_write_1_arg.offset = atoi(args[2]);
				nfs_write_1_arg.size = atoi(args[3]);
				// printf("%s %s %d %d\n", nfs_write_1_arg.filename, nfs_write_1_arg.buffer, nfs_write_1_arg.offset, nfs_write_1_arg.size);
				result_2 = nfs_write_1(&nfs_write_1_arg, clnt);
				if (result_2 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(*result_2 < 0) {
						printf("Wrting Error occured, File not exist or access denied.\n");
					} else {
						printf("%d byte written !\n", *result_2);
					}
				}
				break;
			case 4: // cd
				if(i!=1) {
					printf("usage: cd <dir>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(nfs_cd_1_arg.buffer, args[0]);
				result_4 = nfs_cd_1(&nfs_cd_1_arg, clnt);
				if (result_4 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(*result_4 < 0) {
						printf("Wrong path !\n");
					} else {
						printf("Curr directory changed\n");
					}
				}
				break;
			case 5: // getattr
				if(i!=1) {
					printf("usage: getattr <file_or_dir>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(getattr_1_arg.buffer, args[0]);
				result_5 = getattr_1(&getattr_1_arg, clnt);
				if (result_5 == (bufnode *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("%s\n", result_5->buffer);
				}
				break;
			case 6: // setattr
				if(i!=2) {
					printf("usage: setattr <file_or_dir> <perm_in_octal>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(setattr_1_arg.buffer, args[0]);
				strtok(args[1], "\n");
				setattr_1_arg.size = perm_bit(args[1]);
				result_6 = setattr_1(&setattr_1_arg, clnt);
				if (result_6 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(*result_6 < 0) {
						printf("Error in setting attr\n");
					} else {
						printf("Attr set.\n");
					}
				}
				break;
			case 7: // remove
				if(i!=1) {
					printf("usage: remove <file_or_dir>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(nfs_remove_1_arg.buffer, args[0]);
				result_7 = nfs_remove_1(&nfs_remove_1_arg, clnt);
				if (result_7 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(*result_7 < 0) {
						printf("Error in remove\n");
					} else {
						printf("Removed !\n");
					}
				}
				break;
			case 8: // mkdir
				if(i!=2) {
					printf("usage: mkdir <dir> <perm_in_octal>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(nfs_mkdir_1_arg.buffer, args[0]);
				strtok(args[1], "\n");
				nfs_mkdir_1_arg.size = perm_bit(args[1]);
				result_8 = nfs_mkdir_1(&nfs_mkdir_1_arg, clnt);
				if (result_8 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(*result_8 < 0) {
						printf("Error in creating dirs\n");
					} else {
						printf("Created !\n");
					}
				}
				break;
			case 9: // touch
				if(i!=2) {
					printf("usage: touch <filename> <perm_in_octal>\n");
					break;
				}
				strtok(args[0], "\n");
				strcpy(nfs_touch_1_arg.buffer, args[0]);
				strtok(args[1], "\n");
				nfs_touch_1_arg.size = perm_bit(args[1]);
				result_9 = nfs_touch_1(&nfs_touch_1_arg, clnt);
				if (result_9 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					if(*result_9 < 0) {
						printf("Error in creating dirs\n");
					} else {
						printf("Created !\n");
					}
				}
				break;
			default:
				printf("Invalid Command\n");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	nfs_arya_1 (host);
exit (0);
}
