/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQUARE_H_RPCGEN
#define _SQUARE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	int num;
};
typedef struct args args;

#define SQUARE_CALC 0x1fffffff
#define SQUARE_CALC_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SQUARE 1
extern  int * square_1(args *, CLIENT *);
extern  int * square_1_svc(args *, struct svc_req *);
extern int square_calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SQUARE 1
extern  int * square_1();
extern  int * square_1_svc();
extern int square_calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQUARE_H_RPCGEN */
