/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "square.h"


void
square_calc_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	args  square_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQUARE_CALC, SQUARE_CALC_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Enter Number: \n");
	scanf("%d", &square_1_arg.num);
	result_1 = square_1(&square_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	square_calc_1 (host);
exit (0);
}
